---
- name: Clean up Linux server
  hosts: all
  become: true
  gather_facts: yes

  tasks:
    - name: Clean APT cache (Debian/Ubuntu)
      apt:
        autoclean: yes
        autoremove: yes
        update_cache: no
      when: ansible_os_family == "Debian"

    - name: Clean YUM/DNF cache (RHEL/CentOS/Fedora)
      command: dnf clean all
      when: ansible_os_family == "RedHat"
      changed_when: true
      ignore_errors: true

    - name: Remove old log files
      find:
        paths:
          - /var/log
        patterns: "*.log"
        age: 30d
        recurse: yes
      register: old_logs

    - name: Delete old log files
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ old_logs.files }}"
      when: old_logs.matched > 0

    - name: Remove core dumps if any
      file:
        path: "{{ item }}"
        state: absent
      with_fileglob:
        - /var/crash/core*
        - /core*
      ignore_errors: yes

    - name: Clear thumbnail cache (for desktop systems)
      file:
        path: /home/{{ ansible_user_id }}/.cache/thumbnails
        state: absent
      when: ansible_user_id != 'root'
      ignore_errors: yes
