# ---
# - name: Reboot machine
#   # hosts: "{{ my_hosts | d([]) }}"
#   hosts: all
#   become: true

#   tasks:
#     - name: Reboot machine
#       ansible.builtin.reboot:
#         reboot_timeout: 3600
---
- name: Reboot machine only if required
  hosts: all
  become: true
  gather_facts: yes

  tasks:
    - name: Check if reboot is required (Debian/Ubuntu)
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot if required
      ansible.builtin.reboot:
        reboot_timeout: 3600
      when: reboot_required_file.stat.exists
