---
- name: Check disk space
  hosts: all
  become: true
  gather_facts: no

  tasks:
    - name: Check disk usage of root /
      ansible.builtin.shell:
        cmd: |
          df -Ph / | awk 'NR==2 {print $5 " used, " $4 " free"}'
        executable: /bin/bash
      changed_when: false
      register: disk_usage

    - name: Show disk usage
      debug:
        msg: "📦 Disk usage on {{ inventory_hostname }}: {{ disk_usage.stdout }}"
