---
- name: Display System Information
  hosts: all
  gather_facts: yes
  tasks:
    - name: Print Hostname
      debug:
        msg: "Hostname: {{ ansible_hostname }}"

    - name: Print OS and Version
      debug:
        msg: "OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Print Kernel Version
      debug:
        msg: "Kernel: {{ ansible_kernel }}"

    - name: Print CPU Model
      debug:
        msg: "CPU: {{ ansible_processor[1] }}"

    - name: Print Number of CPUs
      debug:
        msg: "CPU Cores: {{ ansible_processor_cores }}"

    - name: Print Total RAM
      debug:
        msg: "RAM: {{ ansible_memtotal_mb }} MB"

    - name: Print IP Address
      debug:
        msg: "IP Address: {{ ansible_default_ipv4.address }}"

    - name: Print Uptime (using shell)
      shell: uptime -p
      register: uptime_output

    - name: Show Uptime
      debug:
        msg: "Uptime: {{ uptime_output.stdout }}"
