---
- hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Check if updates are available
      shell: apt list --upgradable 2>/dev/null | grep -v "Listing..." | wc -l
      register: upgrade_count
      changed_when: false

    - name: Show available upgrade count
      debug:
        msg: "Packages available for upgrade: {{ upgrade_count.stdout }}"

    - name: Upgrade packages if updates are due
      apt:
        upgrade: dist
      when: upgrade_count.stdout | int > 0
